"""National Water Data Portal (nwdp.nwic.gov.in) - CGWB groundwater levels.

CKAN API, open license, reachable from any IP. Two datasets (docs/sources.md §3b):
  manual quarterly       gwl-manual-quarterly-central-ground-water-board-department
  telemetry six-hourly   ground-water-level-telemetry-daily-cgwb-as-assam (all states)
                         ground-water-level-telemetry-hourly-central-ground-water-board-cgwb (Assam, Bihar)
One CSV per state and period (1991-2020, 2021-2025, 2026-2030). The current-period
files are regenerated by NWDP every day.

Files land in data/raw/nwdp/<manual|telemetry>/<original file name>. A file is
re-downloaded only if NWDP's size or last_modified changed (data/raw/nwdp/manifest.json).

Usage: python -m pipeline.sources.nwdp [--only-current]
"""

from __future__ import annotations

import argparse
import json
import logging
import re
from pathlib import Path

import requests

API = "https://nwdp.nwic.gov.in/api/3/action/package_show"
PACKAGES = {
    "manual": ["gwl-manual-quarterly-central-ground-water-board-department"],
    "telemetry": ["ground-water-level-telemetry-daily-cgwb-as-assam",
                  "ground-water-level-telemetry-hourly-central-ground-water-board-cgwb"],
}
RAW = Path(__file__).resolve().parents[2] / "data" / "raw" / "nwdp"
MANIFEST = RAW / "manifest.json"
CURRENT = re.compile(r"2026\s*[-_]\s*2030")

log = logging.getLogger("nwdp")


def resources(kind: str) -> list[dict]:
    out = []
    for pid in PACKAGES[kind]:
        r = requests.get(API, params={"id": pid}, timeout=60)
        r.raise_for_status()
        for x in r.json()["result"]["resources"]:
            out.append({"kind": kind, "name": x["name"], "url": x["url"],
                        "file": x["url"].rsplit("/", 1)[1], "size": x.get("size"),
                        "last_modified": x.get("last_modified") or x.get("created")})
    return out


def download(res: dict, manifest: dict) -> bool:
    dest = RAW / res["kind"] / res["file"]
    key = f"{res['kind']}/{res['file']}"
    old = manifest.get(key, {})
    if dest.exists() and old.get("size") == res["size"] and old.get("last_modified") == res["last_modified"]:
        return False
    dest.parent.mkdir(parents=True, exist_ok=True)
    tmp = dest.with_suffix(".part")
    with requests.get(res["url"], timeout=900, stream=True) as r:
        r.raise_for_status()
        with open(tmp, "wb") as f:
            for chunk in r.iter_content(1 << 20):
                f.write(chunk)
    tmp.rename(dest)
    manifest[key] = {"size": res["size"], "last_modified": res["last_modified"], "name": res["name"]}
    return True


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--only-current", action="store_true", help="only the 2026-2030 files")
    a = ap.parse_args(argv)
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    manifest = json.loads(MANIFEST.read_text()) if MANIFEST.exists() else {}
    n = 0
    for kind in PACKAGES:
        for res in resources(kind):
            if a.only_current and not CURRENT.search(res["name"] + res["file"]):
                continue
            if download(res, manifest):
                n += 1
                log.info("downloaded %s", res["file"])
            MANIFEST.write_text(json.dumps(manifest, indent=1))
    log.info("%d files updated", n)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
